# Generated by Django 3.2.14 on 2022-11-06 13:47

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid_1', models.BigIntegerField()),
                ('objectid', models.FloatField()),
                ('province', models.CharField(max_length=50)),
                ('const_nam', models.CharField(max_length=50)),
                ('elec_area_field', models.CharField(max_length=50)),
                ('local_auth', models.CharField(max_length=50)),
                ('st_area_sh', models.FloatField()),
                ('st_length_field', models.FloatField()),
                ('const_no', models.FloatField()),
                ('county_nam', models.CharField(max_length=50)),
                ('county_no', models.FloatField()),
                ('st_length1', models.FloatField()),
                ('votes', models.BigIntegerField()),
                ('st_lengt_1', models.FloatField()),
                ('globalid', models.CharField(max_length=38)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', djgeojson.fields.MultiPolygonField()),
            ],
        ),
        migrations.CreateModel(
            name='CdfProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=254)),
                ('descrition', models.CharField(max_length=254)),
                ('phases', models.CharField(choices=[('phase1', 'phase1'), ('phase2', 'phase2'), ('phase3', 'phase3'), ('phase4', 'phase4'), ('phase5', 'phase5')], max_length=150)),
                ('duration', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete'), ('Onprogress', 'Onprogress'), ('Stopped', 'Stopped')], max_length=254)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('propdate', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(max_length=254)),
                ('sectors', models.CharField(max_length=254)),
                ('amount', models.BigIntegerField()),
                ('lat', models.FloatField()),
                ('county_nam', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('lon', models.FloatField()),
                ('geom', djgeojson.fields.MultiPointField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.IntegerField()),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'ContactUs',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ContractorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contr_report', models.FileField(upload_to='document/')),
                ('contr_remark', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('progress', models.BigIntegerField(blank=True, null=True)),
                ('contr_images', models.ImageField(upload_to='images/')),
                ('status', models.CharField(choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete'), ('Onprogress', 'Onprogress'), ('Stopped', 'Stopped')], max_length=254)),
                ('contr_accept', models.CharField(choices=[('accepted', 'accepted'), ('notaccepted', 'notaccepted')], default='notaccepted', max_length=150)),
                ('phases', models.CharField(choices=[('phase1', 'phase1'), ('phase2', 'phase2'), ('phase3', 'phase3'), ('phase4', 'phase4'), ('phase5', 'phase5')], max_length=150)),
                ('finishdate', models.DateField(blank=True, null=True)),
                ('cdfproject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdf.cdfprojects')),
            ],
        ),
        migrations.CreateModel(
            name='EngineerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_report', models.FileField(upload_to='document/')),
                ('engineer_remarks', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('eng_images', models.FileField(upload_to='images/')),
                ('phases', models.CharField(choices=[('phase1', 'phase1'), ('phase2', 'phase2'), ('phase3', 'phase3'), ('phase4', 'phase4'), ('phase5', 'phase5')], max_length=150)),
                ('eng_approve', models.CharField(choices=[('approved', 'approved'), ('notapproved', 'notapproved')], default='notapproved', max_length=150)),
                ('progress', models.BigIntegerField(blank=True, null=True)),
                ('cdfproject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdf.cdfprojects')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('mdate', models.DateField()),
                ('mtime', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Events',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FroudReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, upload_to='reportmedia/%y/%m/%d')),
                ('description', models.TextField()),
                ('geom', djgeojson.fields.PointField()),
            ],
            options={
                'verbose_name_plural': 'FroudReports',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='reportImages/%y/%m/%d')),
                ('description', models.TextField()),
                ('geom', djgeojson.fields.PointField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('opinion', models.CharField(choices=[('Comment', 'Comment'), ('Complain', 'Complain')], max_length=200)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Reports',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('mdate', models.DateField()),
                ('mtime', models.TimeField()),
                ('geom', djgeojson.fields.PointField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'SecurityEvent',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.CharField(choices=[('Comment', 'Comment'), ('Complain', 'Complain')], max_length=200)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete'), ('Onprogress', 'Onprogress'), ('Stopped', 'Stopped')], max_length=200)),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Suggestions',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_report', models.FileField(upload_to='document/')),
                ('project_remark', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('phases', models.CharField(choices=[('phase1', 'phase1'), ('phase2', 'phase2'), ('phase3', 'phase3'), ('phase4', 'phase4'), ('phase5', 'phase5')], max_length=150)),
                ('proj_approve', models.CharField(choices=[('approved', 'approved'), ('notapproved', 'notapproved')], default='notapproved', max_length=150)),
                ('progress', models.BigIntegerField(blank=True, null=True)),
                ('contrdetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdf.contractordetails')),
                ('engdetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdf.engineerdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/EngineerProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.IntegerField()),
                ('skill', models.CharField(max_length=500, null=True)),
                ('salary', models.PositiveIntegerField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/ContractorProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cdf.cdfprojects')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddField(
            model_name='cdfprojects',
            name='project_cont',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdf.contractor'),
        ),
        migrations.AddField(
            model_name='cdfprojects',
            name='project_eng',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdf.engineer'),
        ),
    ]
