# Generated by Django 3.2.14 on 2022-11-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractordetails',
            name='contr_images',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='contractordetails',
            name='contr_report',
            field=models.FileField(upload_to=''),
        ),
    ]
