# Generated by Django 3.2.14 on 2022-11-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdf', '0002_auto_20221107_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractordetails',
            name='contr_images',
            field=models.FileField(upload_to=''),
        ),
    ]
