# Generated by Django 3.2.14 on 2022-11-08 03:38

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cdf', '0005_cdfprojects_project_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdfprojects',
            name='duration',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cdfprojects',
            name='geom',
            field=djgeojson.fields.MultiPointField(null=True),
        ),
        migrations.AlterField(
            model_name='cdfprojects',
            name='remarks',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
