# Generated by Django 3.2.14 on 2022-11-08 03:40

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cdf', '0006_auto_20221108_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdfprojects',
            name='duration',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cdfprojects',
            name='geom',
            field=djgeojson.fields.MultiPointField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cdfprojects',
            name='remarks',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
