# Generated by Django 3.2.14 on 2022-11-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdf', '0007_auto_20221108_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdfprojects',
            name='startdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
